### ISSUE TITLE
Add import shortcut?

### ISSUE THREAD

**Issue by alamboley** [jcward/vscode-haxe#20]
Hey, thanks for your hard work on the extension!

It would be very cool to have in the suggestions a way to make an import!

**Comment by pleclech** [comment]
@alamboley I did not understand, sorry what have you in mind ?

**Comment by alamboley** [comment]
@pleclech  let say i'm using haxe js. And I need the `Document` class, I need to write myself `js.html.Document` or making the `import  js.html.Document;` before being able to use it.

What would be cool is : writing `Docu` and the pressing _auto-complete_ key would suggest to make the import itself. Then I will be able to use it directly.

And it would be perfect if it would not only work with the Haxe core, but any lib in the build.hxml ;)

**Comment by jcward** [comment]
Yes, adding imports is a pain, and iirc, Flash Develop automagically adds them. I believe in Flash Develop (or maybe it's Flash Builder, I forget) if I type `flash.events.Mou`, auto-complete knows that I'm looking for `MouseEvent`, so when I press tab, it does two things:

1) Replaces the fully qualified `flash.events.Mou` with the unqualified `MouseEvent`, and
2) Adds an `import flash.events.MouseEvent;` statement at the top of the file if it doesn't already exist.

(I don't think it handles name conflicts, or maybe if there was already a named class, it wouldn't perform the above steps.) This could be an optional feature via a setting.

Another tool (again, maybe Flash Builder) automagically managed import statements entirely -- kept them in alphabetical order, maintained only those imports in use, maybe even expanded `pack.*` statements, etc.

These are certainly interesting ideas. I'm irritated by keeping imports up to date.

**Comment by alamboley** [comment]
Yeah, Flash Develop needs to haxe the whole package which is a pain compared to Flash Builder or IntelliJ, mostly when I'm not familiar with the library.

> Another tool (again, maybe Flash Builder) automagically managed import statements entirely -- kept them in alphabetical order, maintained only those imports in use, etc.

This would be awesome features too, but I would already be happy with the previous one ;)

**Comment by jcward** [comment]
One thing to keep in mind is that Haxe is more complex than AS3 in that it allows multiple public definitions within a file (so a file is a "module" or some such.) But perhaps that doesn't matter, so sometimes you'd see:

```
import package.MyClass;
import package.MyClass.IMyInterface;
```

As they're both defined in `MyClass.hx`

**Comment by pleclech** [comment]
If you begin type the full qualified name it can be find/complete easily.
But if you write only imcomplete name (as your example typing Docu) i don't think it feasible since you will have to index in advance every package possible just to match Docu !

**Comment by pleclech** [comment]
@jcward don't know if reordering package is a good idea ?
Maybe the order you import them have an importance in a particular project ?

**Comment by jcward** [comment]
@pleclech - yes, there's no good way to index all classes to support short names. I believe that's why the feature is: "Add import statements when completing fully qualified class names"

With the caveats:
- will not add duplicate import statements (but will still collapse those fully qualified names when completed), and
- will not add conflicting short names (and will leave the fully qualified name when completed)

Are there cases where import order matters? I can't imagine that's common? Regardless, I don't think "full import management" feature is important. But even in "adding import statements" we'll inherently choose an order -- either prepend or addend the import statement.

Another possible issue, if you begin with `haxe.Constr` and tab complete it, it'll add `import haxe.Constraint;` but maybe you actually wanted `haxe.Constraint.Function`. But I'm inclined to ignore this issue as well. If the feature is "Add import statements when completing fully qualified class names" -- then I know I have to indicate the full name I want: `haxe.Constraints.Fun`<tab>

**Comment by b005t3r** [comment]
> Regardless, I don't think "full import management" feature is important.

Of course it is. With larger project, files which are change often, many import become unnecessary after some time (imported classes are no longer used), so if you don't remove those the whole file becomes a mess. I think that import management like the one IDEA offers is a must.

**Comment by jcward** [comment]
Hi @b005t3r - we could argue about exactly what's useful and what's too intrusive ala import management. :) But, this particular plugin is in legacy / support mode. We're not likely to be adding major features. The new Haxe plugin for VSCode is being developed [over here](https://github.com/vshaxe/vshaxe) -- you can find it in the [vscode marketplace here](https://marketplace.visualstudio.com/items?itemName=nadako.vshaxe). Under features, it lists unused import removal and import suggestions. Personally, I like that both are user-initiated actions. I feel some IDEs take too much auto-control of import statements.
