### ISSUE TITLE
Images in Marketplace

### ISSUE THREAD

**Issue by joaomoreno** [jcward/vscode-haxe#27]
Hi, VS Code dev here.

We noticed that the images in your `README.md` file are not visible in the [marketplace page](https://marketplace.visualstudio.com/items?itemName=haxedevs.haxe). We are working on fixing that, but in the meanwhile you can work around it by using the markdown syntax: `![alt](image url)`

**Comment by jcward** [comment]
@joaomoreno thanks for the note. Looking at the current syntax, I believe I'm using the `<img>` syntax so I can specify a uniform width for the images. I'm scaling in the browser because scaling animated GIFs typically reduces quality or balloons the file size.

I'll play around with different methods of pre-scaling. Cheers!

**Comment by jcward** [comment]
They appear to be visible now, I'm guessing you guys fixed it. Thanks!
