### ISSUE TITLE
CodeLens support - method reference counting ?

### ISSUE THREAD

**Issue by jarnik** [jcward/vscode-haxe#29]
Is there a chance for making [CodeLens](https://code.visualstudio.com/Docs/languages/csharp)'s method reference counting work for Haxe? Or is it C# only feature?

Anyway, thanks for the plugin!

**Comment by jcward** [comment]
I'd never heard of that, that's an interesting feature. I don't think it's something that the Haxe compiler supports (all the current features depend on the Haxe compiler parsing the project and returning the data.) You could file a feature request with the compiler, but since it's probably a VSCode-only thing (I'm guessing sublime/atom/etc don't support displaying the reference counts) I'd guess it's not likely to be implemented.

Thanks for the suggestion!
